#
# This file contains configuration flags to customize your site
#

# title of your site (displayed in the header)
# name --> title: Hello, I'm Onito‚Ñ¢ üëã
# changes 4 site.name to site.title
title: The Desert Cat Worrior üê±

# Short bio or description (displayed in the header)
description: Nothing but today, Anything but yesterday

# author information refering to: https://goo.gl/iQCi4q
author:
  name: onito x3
  twitter: onito

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/system/Felix.png

# favicon at {{ site.baseurl }}/images/system/{{ site.favicon1 }}
favicon1: Felix.png
favicon2: emoji_duck.png
favicon3: jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: nitt0x0@gmail.com
  facebook:
  flickr:
  github: onitonitonito/onitonitonito.github.io.git
  instagram:
  linkedin:
  pinterest:
  twitter:
  rss: # just type anything here for a working RSS icon

  # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  stackoverflow:

  # channel/<your_long_string> or user/<user-name>
  youtube:

  # anything in your profile username that comes after plus.google.com/
  googleplus:

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: onito3

# Enter your Google Analytics web tracking code to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io
# or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://onitonitonito.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

# unicode permalink problem on title url /:title/ below üò´
# permalink: /:categories/:year/:month/:day/
permalink: /:categories/:year/:month/:day/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# if utf-8 permalink doesn't work correctly. unify all utf-8
encoding: "UTF-8"

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
# Add Gemfile, and make description for {% seo %} tag
# refer: https://goo.gl/xkfn5H

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

# Exclude these files from your production _site
#  - README.md

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
